<?php

namespace TestBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TblproductdataRepository extends EntityRepository
{

}
