services:
  product.repository:
    class: TestBundle\Entity\Repository\ProductRepository
    factory_service: doctrine
    factory_method: getRepository
    arguments:
      - TestBundle\Entity\Product

  product.validator:
    class: TestBundle\Services\ProductValidator
    arguments:
      - @product.repository
