services:
  strProduct.repository:
    class: TestBundle\Entity\Repository\TblproductdataRepository
    factory_service: doctrine
    factory_method: getRepository
    arguments:
      - TestBundle\Entity\Tblproductdata
